### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by SamuelMarks** [tommccallum/oauth2#2]
Started working on it - https://github.com/SamuelMarks/oauth2/tree/windows

But looks like a lot of work to actually get it running. What do you think?

**Comment by tommccallum** [comment]
Not looked into it, so cannot comment.  Is there a particular part that you think seems challenging?

**Comment by SamuelMarks** [comment]
@tommccallum Spent a bunch more time on it today, in #3 you'll note that I've gotten it to build on Windows (with MSVC). Building with maximal warning levels currently works (with no warnings or errors given).

Any idea why it's failing? (it crashes with a `std::runtime_error`)

PS: I also added documentation

**Comment by SamuelMarks** [comment]
Closed by #4
